### Program # 1

In [10]:
print("Hello, Umair!")

Hello, Umair!


### Program # 2

In [ ]:
#Print sum of two numbers
n1 = float(input("Enter first number: "))
n2 = float(input("Enter second number: "))

total = n1 + n2

print(total)

7.0


In [12]:
#Division of two numbers
print("Now, let's divide two numbers.")
n3 = float(input("Enter first number: "))
print("1st number is : ",n3)
n4 = float(input("Enter second number: "))
print("2nd number is : ",n4)

division= n3/n4
if n4 == 0:
    raise ValueError("Cannot divide by zero")
    
    
else: 
    print(division)



Now, let's divide two numbers.
1st number is :  2.0
2nd number is :  3.0
0.6666666666666666


In [13]:
#Multiplication of two numbers
n5 = float(input("Enter first number: "))
n6 = float(input("Enter second number: "))

mul = n5 * n6

print(mul)

32.0


### Program # 3

In [14]:
#Area of Triangle
base = float(input("Enter base of triangle: ")) 
height = float(input("Enter height of triangle: "))
area = 0.5 * base * height  

print("Area of triangle is:", area)

Area of triangle is: 12.0


In [15]:
#Area of a circle

#import math library to use pi constant
import math

radius = float(input("Enter radius of circle: "))

#Calculate area of circle using the formula: area = π * r^2

area_circle = round(math.pi * (radius ** 2), 2)  # rounding to 2 decimal places 

#Print the area of circle

print(f"Area of circle is:{area_circle}")

Area of circle is:153.94


### Program # 4

In [16]:
#Swap two variables
print("Swapping two variables")

a = input("Enter first variable: ")
b = input("Enter second variable: ")

print("Before swapping(a): ",a)
print("Before swapping(b): ",b)

# Swapping using a temporary variable
temp = a
a  =  b
b = temp

print("After swapping(a): ",a)
print("After swapping(b): ",b)


Swapping two variables
Before swapping(a):  2
Before swapping(b):  8
After swapping(a):  8
After swapping(b):  2


### Program # 5

In [17]:
#Generate random number

import random
print("Generating random number between 1 and 100")
random_number = random.randint(1, 100)

print("Random number is:", random_number)

Generating random number between 1 and 100
Random number is: 7


### Program # 6

In [18]:
#Covert Kilometers to Miles

kilometers = float(input("Enter distance in kilometers: "))

# Conversion factor

# 1 kilometer = 0.621371 miles

miles = kilometers * 0.621371

print(f"{kilometers} kilometers is equal to {miles} miles")




10.0 kilometers is equal to 6.21371 miles


### Program # 7

In [19]:
#Convert Celsius to Fahrenheit

celsius = float(input("Enter temperature in Celsius: "))

# Conversion formula: Fahrenheit = (Celsius * 9/5) + 32
fahrenheit = (celsius * 9/5) + 32

print(f"{celsius} Celsius is equal to {fahrenheit} Fahrenheit")

38.0 Celsius is equal to 100.4 Fahrenheit


### Program # 8

In [20]:
# Display Calendar of a month

import calendar

year = input("Enter year: ")
month = input("Enter month (1-12): ")

cal = calendar.month(int(year), int(month))

print(cal)

    August 2025
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30 31



In [21]:
#Calendar of a year
import calendar
year = int(input("Enter year: "))

cal = calendar.calendar(year)


print(cal)



                                  2025

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                      1  2                      1  2
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       3  4  5  6  7  8  9
13 14 15 16 17 18 19      10 11 12 13 14 15 16      10 11 12 13 14 15 16
20 21 22 23 24 25 26      17 18 19 20 21 22 23      17 18 19 20 21 22 23
27 28 29 30 31            24 25 26 27 28            24 25 26 27 28 29 30
                                                    31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                1  2  3  4                         1
 7  8  9 10 11 12 13       5  6  7  8  9 10 11       2  3  4  5  6  7  8
14 15 16 17 18 19 20      12 13 14 15 16 17 18       9 10 11 12 13 14 15
21 22 23 24 25 26 27      19 20 21 22 23 24 

### Program # 9

In [22]:
#To solve quadratic equation
import cmath    
print("Solving quadratic equation of the form ax^2 + bx + c = 0")
a = float(input("Enter coefficient a: "))
print("Coefficient a is:", a)
b = float(input("Enter coefficient b: "))
print("Coefficient b is:", b)
c = float(input("Enter coefficient c: "))
print("Coefficient c is:", c)
# Calculate the discriminant

d = (b**2) - (4*a*c)
# Find two solutions    
sol1 = (-b + cmath.sqrt(d)) / (2 * a)
sol1Round= round(sol1.real, 2),round(sol1.imag, 2)
print(f"The first solution is: {sol1Round}")

sol2 = (-b - cmath.sqrt(d)) / (2 * a)
sol2Round = round(sol2.real, 2),round(sol2.imag, 2)
print(f"The second solution is: {sol2Round}")


print("*****************End of the program*****************")

Solving quadratic equation of the form ax^2 + bx + c = 0
Coefficient a is: 3.0
Coefficient b is: 5.0
Coefficient c is: 7.0
The first solution is: (-0.83, 1.28)
The second solution is: (-0.83, -1.28)
*****************End of the program*****************


### Program # 10

In [23]:
# without using a temporary variable
a = input("Enter first variable: ")
b = input("Enter second variable: ")

print("Before swapping(a): ",a)
print("Before swapping(b): ",b)

a, b = b, a
print("After swapping(a): ",a)
print("After swapping(b): ",b)

Before swapping(a):  5
Before swapping(b):  6
After swapping(a):  6
After swapping(b):  5


### Program # 11

In [27]:
#check positive or negative number and zero
n = float(input("Enter a number: "))
if n > 0:
    print("The number is positive.")    
elif n < 0:
    print("The number is negative.")        
else:
    print("The number is zero.")
    

The number is positive.


### Program # 12

In [29]:
#Check if a number is even or odd
n = int(input("Enter a number: "))
print("Number:", n)
if n % 2 == 0:
    print(f"{n} is an even number.")
else:
    print(f"{n} is an odd number.") 

Number: 45
45 is an odd number.


### Program # 13

In [35]:
#Check leap year
year = int(input("Enter a year: "))

#logic to check if a year is a leap year
# A year is a leap year if it is divisible by 4, but not divisible by 100, unless it is also divisible by 400.
# For example, 2000 and 2012 are leap years, but 1900 is not a leap year.

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(f"{year} is a leap year.")

else:
    print(f"{year} is not a leap year.")



2025 is not a leap year.


### Program # 14

In [37]:
#Check prime number

num = int(input("Enter a number: "))

if num > 1:
    for i in range(2, int(num**0.5) + 1):
        if (num % i) == 0:
            print(f"{num} is not a prime number.")
            break
    else:
        print(f"{num} is a prime number.")

15 is not a prime number.


### Program # 15

In [39]:
#Check prime number in a range
start = int(input("Enter the start of the range: "))
end = int(input("Enter the end of the range: "))    

for num in range(start, end + 1):
    if num > 1:
        for i in range(2, int(num**0.5) + 1):
            if (num % i) == 0:
                break
        else:
            print(f"{num} is a prime number.")
    else:
        print(f"{num} is not a prime number.")

2 is a prime number.
3 is a prime number.
5 is a prime number.
7 is a prime number.
11 is a prime number.
13 is a prime number.
17 is a prime number.
19 is a prime number.
23 is a prime number.
29 is a prime number.


### Program # 16

In [5]:
#Factorial of a number
num = int(input("Enter a number to find its factorial: "))

def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

print(f"The factorial of {num} is {factorial(num)}")   

The factorial of 6 is 720


### Program # 17

In [6]:
#Multiplication table
num = int(input("Enter a number to generate its multiplication table: "))

for i in range(1, 11):

    print(f"{num} x {i} = {num * i}")
    

7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70


### Program # 18

In [15]:
#Fibonacci series
#initialize the first two terms
n1,n2 = 0, 1

count = 0

n_terms = int(input("Enter the number of terms in the Fibonacci series: "))

while count < n_terms:
    print(n1, end=' ')
    nth = n1 + n2
    # update values
    n1 = n2
    n2 = nth
    count += 1

0 1 1 2 3 5 8 13 21 34 

### Program # 19

In [19]:
#Check Armstrong number
#An Armstrong number (or narcissistic number) is a number that is equal     
# to the sum of its own digits each raised to the power of the number of digits. 
# For example, 153 is an Armstrong number because 1^3 + 5^3 + 3^3 = 153.
num = int(input("Enter a number to check if it is an Armstrong number: "))
power = len(str(num))
total = 0
for digit in str(num):
    total += int(digit) ** power
if total == num:
    print(f"{num} is an Armstrong number.")
else:
    print(f"{num} is not an Armstrong number.")


153 is an Armstrong number.


### Program # 20

In [18]:
#Check Armstrong numbers in an interval
start = int(input("Enter the start of the interval: "))
end = int(input("Enter the end of the interval: "))
for num in range(start, end + 1):
    power = len(str(num))
    total = 0
    for digit in str(num):
        total += int(digit) ** power
    if total == num:
        print(f"{num} is an Armstrong number.")
    else:
        print(f"{num} is not an Armstrong number.")

4 is an Armstrong number.
5 is an Armstrong number.
6 is an Armstrong number.
7 is an Armstrong number.
8 is an Armstrong number.
9 is an Armstrong number.
10 is not an Armstrong number.
11 is not an Armstrong number.
12 is not an Armstrong number.
13 is not an Armstrong number.
14 is not an Armstrong number.


### Program # 21

In [17]:
#Sum of natural numbers upto certain limit
#Natural numbers are the positive integers starting from 1.

limit = int(input("Enter the limit: "))

add = 0

for i in range(1, limit + 1):
    add += i
print(f"The sum of natural numbers up to {limit} is: {add}")


The sum of natural numbers up to 70 is: 2485


### Program # 22

In [1]:
#calculate LCM
def lcm(x, y):
    if x > y:
        greater = x
    else:
        greater = y

    while True:
        if greater % x == 0 and greater % y == 0:
            lcm = greater
            break
        

    return lcm
# Get input from the user

num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
print(f"The LCM of {num1} and {num2} is: {lcm(num1, num2)}")

The LCM of 6 and 24 is: 24


### Program # 23

In [3]:
#Calculate GCD
#HCF(highest Common Factor) or GCD(Greatest Common Divisor) is the largest number that divides two or more numbers without leaving a remainder.
# The GCD can be calculated using the Euclidean algorithm.  

def gcd(x, y):
    while y:
        x, y = y, x % y
    return x
# Get input from the user
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
num3 = int(input("Enter third number: "))
print(f"The GCD of {num1}, {num2}, and {num3} is: {gcd(gcd(num1, num2), num3)}")


The GCD of 2, 4, and 8 is: 2


### Program # 24

In [8]:
#Convert decimal to binary,octal, and hexadecimal

print("Converting decimal to binary, octal, and hexadecimal")
decimal = int(input("Enter a decimal number: "))
if decimal < 0:
    raise ValueError("Please enter a non-negative integer.")

binary = bin(decimal)[2:] # Convert to binary and remove '0b' prefix
octal = oct(decimal)[2:]   # Convert to octal and remove '0o    ' prefix
hexadecimal = hex(decimal)[2:] # Convert to hexadecimal and remove '0x' 


print(f"Binary: {binary}")
print(f"Octal: {octal}")        
print(f"Hexadecimal: {hexadecimal}")


Converting decimal to binary, octal, and hexadecimal
Binary: 101011001
Octal: 531
Hexadecimal: 159


### Program # 25

In [12]:
#Find ASCII value of a character

char = input("Enter a character: ")
ascii_value = ord(char) # Get ASCII value using ord() function

print(f"The ASCII value of '{char}' is : {ascii_value}")

The ASCII value of 'P' is : 80


### Program # 26

In [20]:
#Simple calculator

print("********Simple Calculator**********")

print("Select operation:")
print("1. Addition")    
print("2. Subtraction")
print("3. Multiplication")
print("4. Division")


while True:
    choice = input("Enter choice (1/2/3/4): ")


    if choice in ('1', '2', '3', '4'):
     num1 = float(input("Enter first number: "))
     num2 = float(input("Enter second number: "))

    if choice == '1':
      result = num1 + num2
      print(f"The result of addition is: {result}")
    elif choice == '2':
        result = num1 - num2
        print(f"The result of subtraction is: {result}")
    elif choice == '3':
        result = num1 * num2
        print(f"The result of multiplication is: {result}")
    elif choice == '4':
        if num2 == 0:
            raise ValueError("Cannot divide by zero")
        result = num1 / num2
        print(f"The result of division is: {result}")

    next_calculation = input("Do you want to perform another calculation? (yes/no): ")
    if next_calculation.lower() != 'yes':
        print("Exiting the calculator. Goodbye!")
        break



********Simple Calculator**********
Select operation:
1. Addition
2. Subtraction
3. Multiplication
4. Division


The result of multiplication is: 10.0
Exiting the calculator. Goodbye!


### Program # 27

In [ ]:
#Display Fibonacci sequence using recursion

def fibonacci(n):
    if n <= 0:
        return []
    elif n == 1:
        return [0]
    elif n == 2:
        return [0, 1]
    else:
        fib_sequence = fibonacci(n - 1)  # Get the Fibonacci sequence up to n-1 terms
        # Append the next term to the sequence
        fib_sequence.append(fib_sequence[-1] + fib_sequence[-2])
        return fib_sequence
    
n_terms = int(input("Enter the number of terms in the Fibonacci sequence: "))
fib_sequence = fibonacci(n_terms)
print(f"The Fibonacci sequence with {n_terms} terms is: {fib_sequence}")

The Fibonacci sequence with 5 terms is: [0, 1, 1, 2, 3]


### Program # 28

In [3]:
#Factorial using recursion
def recur_factorial(n):
    if n == 1:
        return n
    else:
        return n*recur_factorial(n-1)

num = int(input("Enter a number: "))

if num<0:
    print("Factorial does not exist for negative numbers")
elif num==0:
    print("Factorial of 0 is 1")
else:
    print(f"The factorial of {num}, is {recur_factorial(num)}")

The factorial of 5, is 120


### Program # 29

In [10]:
#Body Mass index
print("*****WELCOME TO BMI CALCULATOR******")
weight = float(input("Enter Your Weight(kg): "))
height= float(input("Enter Your Height(meters): "))

BMI = round((weight/height**2),2)

print("Your BMI is:" ,BMI)

if BMI<18.5:
    print("You are underweight.")
elif 18.5 < BMI < 24.9:
    print("Your Weight is Normal.")

else:
    print("You are Obese.")

*****WELCOME TO BMI CALCULATOR******
Your BMI is: 24.22
Your Weight is Normal.


### Program # 30

In [12]:
#natural logarithm of any number

import math

num = float(input('Enter a number: '))

if num<0:
    print("Please enter a Positive number")
else:
    result =round(math.log(num),2)
    print(f"Natural log of {num} is {result}")

Natural log of 50.0 is 3.91


### Program # 31

In [ ]:
#Cube sum of first n natural numbers
num = int(input("Enter the value of n: "))

result=[i**3 for i in range(1,num+1)]
total = 0
for value in result:
    total += value

print(result)

print(f"Cube Sum of 1st n natural numbers is: {total}")




[1, 8, 27, 64, 125, 216]
Cube Sum of 1st n natural numbers is 441


### Program # 32

In [24]:
#find sum of array elements in array

arr = [2,4,6,8]

total= 0
for value in arr:
    total += value



print(f"The Sum of array is: {total}")

The Sum of array is: 20


### Program # 33

In [29]:
#Largest element in an array
arr = [5,3,25,50,13]

largest_ele = arr[0]

for element in arr:
    if element>largest_ele:
        largest_ele = element

print(f"Largest element in array is: {largest_ele}")

Largest element in array is: 50


### Program # 34

In [2]:
#left Array Rotation
arr = [1,2,3,4,5]

k = 2  # Number of rotations


left_rotated = arr[k:] + arr[:k]
print("Left Rotation:", left_rotated)  # [3, 4, 5, 1, 2]




Left Rotation: [3, 4, 5, 1, 2]


### Program # 35

In [5]:
#Right Array Rotation
arr = [1,2,3,4,5]

k = 2

right_rotated = arr[-k:] + arr[:-k]

print("Right Rotation:" ,right_rotated)



Right Rotation: [4, 5, 1, 2, 3]


### Program # 36

In [ ]:
#Check if array is array  is monotonic
def is_monotonic(arr):
    increasing = decreasing = False

    for i in range(1,len(arr)):
        if arr[i] > arr[i-1]:
            increasing = True

        elif arr[i] < arr[i-1]:
            decreasing = True
        
    return not(increasing and decreasing) ## It’s monotonic only if it’s increasing OR decreasing, but not both

arr1 = [1,2,3,3,4]
arr2 = [3,2,1,0]
arr3 = [1,8,7,3,5]

print("arr1 is monotonic :",is_monotonic(arr1))
print("arr2 is monotonic :",is_monotonic(arr2))
print("arr3 is monotonic :",is_monotonic(arr3))

arr1 is monotonic : True
arr2 is monotonic : False
arr3 is monotonic : False


### Program # 37

In [4]:
#Addition of matrices
#Use numpy library
import numpy as np

A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ])

B = np.array([
    [9,8,4],
    [4,2,6],
    [6,2,1]
])

result = A+B

print(result)



[[10 10  7]
 [ 8  7 12]
 [13 10 10]]


### Program # 38

In [7]:
#Multiplication of matrices
import numpy as np

A = np.array([
    [1,2,3],
    [4,5,4],
    [3,6,2]
])

B = np.array([
    [7,8],
    [4,5],
    [2,3]
])

result = np.dot(A,B)

print(result)

[[21 27]
 [56 69]
 [49 60]]


### Program # 39

In [9]:
#Transpose of a matrix

import numpy as np 

A = np.array([
    [2,4,9],
    [7,9,5]
])

result = np.transpose(A)

print(result)

[[2 7]
 [4 9]
 [9 5]]


### Program # 40

In [31]:
#Sort words in alphabetically order

my_str = "Umair,Ahmad,Numan,Kashir,Zohaib,hassan"

#break string into list of words
words = [word.capitalize() for word  in my_str.split(",")]

words.sort()

#sorted_names = ",".join(name_list)

print("Sorted Words are:")
for word in words:
    print(word)


Sorted Words are:
Ahmad
Hassan
Kashir
Numan
Umair
Zohaib


### Program # 41

In [7]:
def remove_punctuation(text):
    punctuation = r'''!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~'''
    result = ''
    for char in text:
        if char not in punctuation:
            result += char
    return result

s = "Hello, world! How's it going?"
clean_s = remove_punctuation(s)
print(clean_s)


Hello world Hows it going


### Program # 42

In [1]:
#Chech number is Disarium
def is_disarium(num):
    digits = str(num)
    total = 0
    for i, digit in enumerate(digits, start=1):
        total += int(digit) ** i
    return total == num

test_nums = [135, 175, 89, 80]

for n in test_nums:
    if is_disarium(n):
        print(f"{n} is a Disarium Number")
    else:
        print(f"{n} is NOT a Disarium Number")



135 is a Disarium Number
175 is a Disarium Number
89 is a Disarium Number
80 is NOT a Disarium Number


### Program # 43

In [3]:
#Check disarium numbers in a range

def is_disarium(num):
    digits = str(num)
    total = 0
    for i, digit in enumerate(digits, start=1):
        total += int(digit) ** i
    return total == num


for n in range(130,140):
    if is_disarium(n):
        print(f"{n} is a Disarium Number")
    else:
        print(f"{n} is NOT a Disarium Number")


130 is NOT a Disarium Number
131 is NOT a Disarium Number
132 is NOT a Disarium Number
133 is NOT a Disarium Number
134 is NOT a Disarium Number
135 is a Disarium Number
136 is NOT a Disarium Number
137 is NOT a Disarium Number
138 is NOT a Disarium Number
139 is NOT a Disarium Number


### Program # 44

In [ ]:
#Happy numbers
def is_happy(num):
    seen = set()
    while num != 1 and num not in seen:
        seen.add(num)
        num = sum(int(digit)**2 for digit in str(num))
    return num == 1


test_nums = [19, 20, 7]

for n in test_nums:
    if is_happy(n):
        print(f"{n} is a Happy Number")
    else:
        print(f"{n} is NOT a Happy Number")


19 is a Happy Number
20 is NOT a Happy Number
7 is a Happy Number


### Program # 45

In [7]:
#Happy numbers in a range
def is_happy(num):
    seen = set()
    while num !=1 and num not in seen:
        seen.add(num)
        num = sum(int(digit)**2 for digit in str(num))
    return num == 1
    
for n in range(15,20):
    if is_happy(n):
        print(f"{n} is a Happy number.")

    else:
        print(f"{n} is not a Happy number.")

15 is not a Happy number.
16 is not a Happy number.
17 is not a Happy number.
18 is not a Happy number.
19 is a Happy number.


### Program # 46

In [11]:
#Determine Harshad number 
def is_harshad(num):
    #calculate sum of digits of a number

    digit_sum = sum(int(digit) for digit in str(num))

    return num % digit_sum == 0

num = int(input("Enter a number: "))

if is_harshad(num):
    print(f"{num} is a Harshad number.")
else:
    print(f"{num} is not a Harshad number.")



18 is a Harshad number.


### Program # 47

In [34]:
#Determine pronic numbers
def is_pronic(num):
    for n in range(1,int(num**0.5)+1):
        if n * (n+1) == num:
            return True
    return False
      

for i in range(15,50):
    if is_pronic(i):
        
        print(i,end=",")
    
       

20,30,42,

### Program # 48

In [35]:
# Sum of numbers in a list

numbers = [10,25,15,20,30]

sum = 0

for i in numbers:
    sum += i

print("sum of numbers in a list: ",sum)

sum of numbers in a list:  100


### Program # 49

In [38]:
#Multiply numbers in list
numbers = [2,3,6,5]

mul = 1

for i in numbers:
    mul *= i

print("Multiply of numbers in a list: ", mul)

Multiply of numbers in a list:  180


### Program # 50

In [47]:
# Smallest number in a list

numbers = [-200,45,-75,30,-23]

smallest = numbers[0]
for i in numbers:
    if i < smallest:
        smallest = i

print("The smallest number in a list is: ",smallest)


The smallest number in a list is:  -200
